# ==================
# Project Details
# ==================
name: "Onbe_microbatchSnowflake"
config-version: 2
require-dbt-version:
- "1.9.3"
version: "0.1"
profile: "prophecy-default"

# ==================
# File Path Configs
# ==================
clean-targets:
- "target"
- "dbt_modules"
- "logs"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
macro-paths:
- "macros"
target-path: "target"
