# ==================
# Project Details
# ==================
name: "Onbe_microbatchSnowflake"
config-version: 2
require-dbt-version:
- ">=1.8.0"
- "<2.0.0"
version: "0.13.0"
profile: "prophecy-default"

# ==================
# File Path Configs
# ==================
clean-targets:
- "target"
- "dbt_modules"
- "logs"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars: {}

# ============
# Run Hooks
# ============
on-run-end:
- "{{ log_results( results) }}"

# ============
# Misc
# ============
dispatch: []
