name: Onbe_microbatchSnowflake
description: ''
version: 0.13.0
author: best.neil@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/process_iot_incrementally:
    name: process_iot_incrementally
    description: ''
    fabricUID: 25547
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0/10 * * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2025-04-15 19:42:08'
    author: best.neil@prophecy.io
    models: []
    sqlProjects:
    - '44652'
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-04-04 20:09:22'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/IOT_BATCHES:
    name: IOT_BATCHES
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: LOADED_AT
        dataType:
          type: Timestamp
      - name: DATE
        dataType:
          type: Date
      - name: N_RECORDS_LOADED
        dataType:
          type: Number
      - name: REPORTED_AT
        dataType:
          type: Timestamp
    description: null
    author: best.neil@prophecy.io
    files:
    - models/IOT_BATCHES.sql
    - .prophecy/ide/models/IOT_BATCHES.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2025-04-15 23:52:40'
  .prophecy/metadata/sqlmodels/IOT_INCREMENTAL:
    name: IOT_INCREMENTAL
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: DEVICE_ID
        dataType:
          type: String
      - name: PLANT_ID
        dataType:
          type: String
      - name: TAG_NAME
        dataType:
          type: String
      - name: TS
        dataType:
          type: Timestamp
      - name: VALUE
        dataType:
          type: Float
      - name: ENGINEERING_UNITS
        dataType:
          type: String
      - name: DATE
        dataType:
          type: Date
      - name: LOADED_AT
        dataType:
          type: Timestamp
    description: null
    author: best.neil@prophecy.io
    files:
    - models/IOT_INCREMENTAL.sql
    - .prophecy/ide/models/IOT_INCREMENTAL.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2025-04-15 23:53:48'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: best.neil@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2025-04-04 20:09:25'
  .prophecy/metadata/sqlmacros/log_results:
    name: log_results
    macroType: expression
    description: null
    author: best.neil@prophecy.io
    files:
    - macros/log_results.sql
    - .prophecy/ide/macros/log_results.json
    - macros/macros.yml
    createdAt: '2025-04-07 20:21:17'
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/ONBE_DEMO_DEV_PUBLIC:
    name: ONBE_DEMO_DEV.PUBLIC
    description: null
    author: best.neil@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2025-05-09 16:10:00'
    tables: []
  .prophecy/metadata/sqlsources/ONBE_DEMO_PROD_PUBLIC:
    name: ONBE_DEMO_PROD.PUBLIC
    description: null
    author: best.neil@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2025-05-09 16:10:00'
    tables: []
  .prophecy/metadata/sqlsources/_ONBE_DEMO_env_var_DBT_TARGET_DEV__PUBLIC:
    name: _ONBE_DEMO_env_var_DBT_TARGET_DEV_.PUBLIC
    description: null
    author: best.neil@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2025-05-12 16:48:16'
    tables:
    - name: IOT
      schema:
        entityType: ''
        providerType: snowflake
        fields:
        - name: DEVICE_ID
          dataType:
            type: String
        - name: PLANT_ID
          dataType:
            type: String
        - name: TAG_NAME
          dataType:
            type: String
        - name: TS
          dataType:
            type: Timestamp
        - name: VALUE
          dataType:
            type: Float
        - name: ENGINEERING_UNITS
          dataType:
            type: String
        - name: DATE
          dataType:
            type: Date
        - name: LOADED_AT
          dataType:
            type: Timestamp
      description: IoT sensor data capturing measurements from devices across various
        plants, enabling monitoring and analysis of operational performance.
      author: best.neil@prophecy.io
      createdAt: '2025-05-12 16:48:16'
      tableType: table
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: best.neil@prophecy.io
  createdAt: '2025-04-04 20:09:22'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
