snowflake:
  target: DEV
  outputs:
    DEV:
      type: snowflake
      account: tu22760.ap-south-1.aws
      # User/password auth
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      # authenticator: username_password_mfa
      role: ACCOUNTADMIN
      database: ONBE_DEMO_DEV
      warehouse: DE_WAREHOUSE
      schema: PUBLIC
      threads: 1
      client_session_keep_alive: False
      query_tag: onbe
      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
    PROD:
      type: snowflake
      account: tu22760.ap-south-1.aws
      # User/password auth
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      # authenticator: username_password_mfa
      role: ACCOUNTADMIN
      database: ONBE_DEMO_PROD
      warehouse: DE_WAREHOUSE
      schema: PUBLIC
      threads: 1
      client_session_keep_alive: False
      query_tag: onbe
      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      # trivial commit
