---
version: 2
sources:
- name: "_TARGET_DATABASE_.PUBLIC"
  database: "{{ 'ONBE_DEMO_' ~ env_var( 'DBT_TARGET', 'DEV') }}"
  schema: "PUBLIC"
  tables:
  - name: "IOT"
    description: "IoT sensor data capturing measurements from devices across plants,\
      \ enabling real-time monitoring and analysis of operational performance."
    columns:
    - name: "DEVICE_ID"
      description: "Unique identifier for the IoT device"
      dataType:
        type: "String"
    - name: "PLANT_ID"
      description: "Identifier for the plant where the device is located"
      dataType:
        type: "String"
    - name: "TAG_NAME"
      description: "The name of the tag associated with the IoT device"
      dataType:
        type: "String"
    - name: "TS"
      description: "Timestamp indicating when the data was recorded"
      dataType:
        type: "Timestamp"
    - name: "VALUE"
      description: "The measured value from the IoT device"
      dataType:
        type: "Float"
    - name: "ENGINEERING_UNITS"
      description: "The units of measurement for the device's value"
      dataType:
        type: "String"
    - name: "DATE"
      description: "The date when the data was recorded"
      dataType:
        type: "Date"
    - name: "LOADED_AT"
      description: "Timestamp indicating when the data was loaded into the system"
      dataType:
        type: "Timestamp"
    type: "table"
