---
version: 2
sources:
- name: "ONBE_DEMO_DEV.PUBLIC"
  database: "ONBE_DEMO_DEV"
  schema: "PUBLIC"
  config:
    enabled: true
  tables:
  - name: "IOT"
    description: "IoT sensor data capturing measurements from devices across various\
      \ plants, enabling real-time monitoring and analysis of operational metrics."
    quoting:
      identifier: true
    columns:
    - name: "DEVICE_ID"
      description: "Unique identifier for the IoT device"
      dataType:
        type: "String"
    - name: "PLANT_ID"
      description: "Identifier for the plant where the device is located"
      dataType:
        type: "String"
    - name: "TAG_NAME"
      description: "Name of the tag associated with the IoT device"
      dataType:
        type: "String"
    - name: "TS"
      description: "Timestamp indicating when the data was recorded"
      dataType:
        type: "Timestamp"
    - name: "VALUE"
      description: "The measured value from the IoT device"
      dataType:
        type: "Float"
    - name: "ENGINEERING_UNITS"
      description: "The units of measurement for the device's value"
      dataType:
        type: "String"
    - name: "DATE"
      description: "The date when the data was recorded."
      dataType:
        type: "Date"
    - name: "LOADED_AT"
      description: "Timestamp indicating when the data was loaded into the system"
      dataType:
        type: "Timestamp"
  - name: "IOT_BATCHES"
    description: "Records of IoT data batches, capturing the volume of data loaded\
      \ and the associated timestamps for reporting and loading activities."
    columns:
    - name: "LOADED_AT"
      description: "Timestamp indicating when the batch was loaded"
      dataType:
        type: "Timestamp"
    - name: "YEAR"
      description: "The year in which the records were loaded"
      dataType:
        type: "Number"
    - name: "MONTH"
      description: "The month during which the records were loaded"
      dataType:
        type: "Number"
    - name: "N_RECORDS_LOADED"
      description: "Total number of records successfully loaded in the batch"
      dataType:
        type: "Number"
    - name: "REPORTED_AT"
      description: "Timestamp indicating when the batch was reported"
      dataType:
        type: "Timestamp"
