---
version: 2
sources:
- name: "ONBE_DEMO_' ~ var( 'DBT_TARGET') ~ '.PUBLIC"
  database: "ONBE_DEMO_' ~ var( 'DBT_TARGET') ~ '"
  schema: "PUBLIC"
  tables:
  - name: "IOT"
    columns: []
    type: "table"
- name: "ONBE_DEMO_DEV.PUBLIC"
  database: "ONBE_DEMO_DEV"
  schema: "PUBLIC"
  tables:
  - name: "IOT"
    columns: []
    type: "table"
- name: "ONBE_DEMO_PROD.PUBLIC"
  database: "ONBE_DEMO_PROD"
  schema: "PUBLIC"
  tables:
  - name: "IOT"
    columns: []
    type: "table"
