CREATE OR REPLACE TRANSIENT TABLE

    ONBE_DEMO_{{ var("DBT_TARGET") }}.PUBLIC.DBT_LOAD_LOG (

    DBT_INVOCATION_ID STRING,
    SNOWFLAKE_QUERY_ID STRING,
    DBT_RELATION_NAME STRING,
    LOAD_START_TS TIMESTAMP,
    LOAD_END_TS TIMESTAMP,
    LOAD_STATUS STRING,
    RESULT_MESSAGE STRING,
    N_ROWS_AFFECTED NUMBER,
    CREATED_AT_TS TIMESTAMP,
    UPDATED_AT_TS TIMESTAMP,
    CREATED_BY_USER STRING

);
