---
version: 2
models:
- name: "IOT_BATCHES"
  columns:
  - name: "LOADED_AT"
    tests: []
    dataType:
      type: "Timestamp"
  - name: "DATE"
    tests: []
    dataType:
      type: "Date"
  - name: "N_RECORDS_LOADED"
    tests: []
    dataType:
      type: "Number"
  - name: "REPORTED_AT"
    tests: []
    dataType:
      type: "Timestamp"
  tests: []
- name: "IOT_INCREMENTAL"
  columns:
  - name: "PLANT_ID"
    dataType:
      type: "String"
  - name: "VALUE"
    dataType:
      type: "Float"
  - name: "DEVICE_ID"
    dataType:
      type: "String"
  - name: "TAG_NAME"
    dataType:
      type: "String"
  - name: "LOADED_AT"
    dataType:
      type: "Timestamp"
  - name: "ENGINEERING_UNITS"
    dataType:
      type: "String"
  - name: "DATE"
    dataType:
      type: "Date"
  - name: "TS"
    dataType:
      type: "Timestamp"
  tests: []
